### PR TITLE
missing gx 

### PR DESCRIPTION
**Pull request by Avika1804**
http://gregofacsimil.free.fr/01-Restitution/Repons/Repons-en-pdf/28-In-Sexagesima/06-Immisit-Dominus-soporem.pdf

### CODE REVIEW

**Comment by jakubjelinek** [comment]
Marek has fixed this already.

**Comment by Avika1804** [comment]
THANKS, but what did I do wrong?

**Comment by jakubjelinek** [comment]
Nothing, just Marek fixed it first.  It actually doesn't matter that much who fixes it first, but which pull request I merge first...

**Comment by Avika1804** [comment]
and for this shit what should I do?
https://github.com/Avika1804/Editio-Sti-Wolfgangi/pull/14

**Pull request closed without merging**
